# Generated by Django 3.2.6 on 2021-08-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210807_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
